`timescale 1ns / 1ps
////////////////////////////////////////////////////////////////////////////////--
// Company: 
// Engineer: 
// 
// Create Date: 2026/08/25
// Design Name: Pure Verilog Top Level GPGPU SoC Wrapper
// Module Name: top
// Project Name: fpga-gpu (Accelerated Computing with Linux Kernel vGPU-Core)
// Target Devices: Xilinx Artix-7 (XC7A200T-2FBG484)
// Tool Versions: Vivado 2026+
// Description: 
//   Pure Verilog Top-Level Module for FPGA-GPU SoC:
//   - PCIe Gen2 x2 XDMA Subsystem (xdma_0)
//   - 64-bit to 256-bit AXI Data Width Converter (axi_dwidth_converter_0)
//   - 256-bit 2-Slave to 1-Master AXI Crossbar Interconnect (axi_crossbar_0)
//   - 1GB DDR3 VRAM Controller (mig_7series_0 at 0x8000_0000)
//   - RISC-V Command Processor SoC (riscv_cp_system with 16KB BRAM Mailbox at 0x3F00)
//   - GPGPU Streaming Multiprocessor (gpu_compute_core with Hardware Warp Scheduler)
//   - Dual-Port Framebuffer VRAM (framebuffer_ram)
//   - SiI9134 HDMI 1080P@60Hz Display Pipeline (hdmi_top)
////////////////////////////////////////////////////////////////////////////////--

module top (
    // PCIe Differential Reference Clock (Bank 216 MGTREFCLK0: F10/E10)
    input  wire        sys_clk_clk_p,
    input  wire        sys_clk_clk_n,
    input  wire        sys_rst_n,

    // PCIe Transceiver Lanes (PCIe Gen2 x2)
    input  wire [1:0]  pci_exp_rxp,
    input  wire [1:0]  pci_exp_rxn,
    output wire [1:0]  pci_exp_txp,
    output wire [1:0]  pci_exp_txn,

    // DDR3 SDRAM Physical Pins (Bank 34/35 1GB 32-bit MT41J256M16HA x2)
    inout  wire [31:0] ddr3_dq,
    inout  wire [3:0]  ddr3_dqs_n,
    inout  wire [3:0]  ddr3_dqs_p,
    output wire [14:0] ddr3_addr,
    output wire [2:0]  ddr3_ba,
    output wire        ddr3_ras_n,
    output wire        ddr3_cas_n,
    output wire        ddr3_we_n,
    output wire        ddr3_reset_n,
    output wire [0:0]  ddr3_ck_p,
    output wire [0:0]  ddr3_ck_n,
    output wire [0:0]  ddr3_cke,
    output wire [3:0]  ddr3_dm,
    output wire [0:0]  ddr3_odt,

    // SiI9134 HDMI Physical Display Ports (Mapped to constrs/hdmi.xdc)
    output wire        hdmi_nreset,
    (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 hdmi_clk CLK" *)
    (* X_INTERFACE_PARAMETER = "FREQ_HZ 148500000" *)
    output wire        hdmi_clk,
    output wire        hdmi_hs,
    output wire        hdmi_vs,
    output wire        hdmi_de,
    output wire [23:0] hdmi_d,
    inout  wire        hdmi_scl,
    inout  wire        hdmi_sda,
    output wire        hdmi_init_done
);

    // -------------------------------------------------------------------------
    // 1. PCIe Reference Clock Buffer (IBUFDS_GTE2 Primitive)
    // -------------------------------------------------------------------------
    wire pcie_ref_clk;
    IBUFDS_GTE2 u_ibufds_gte2 (
        .I     (sys_clk_clk_p),
        .IB    (sys_clk_clk_n),
        .CEB   (1'b0),
        .O     (pcie_ref_clk),
        .ODIV2 ()
    );

    // System Clocks & Resets generated by XDMA IP
    wire axi_aclk;
    wire axi_aresetn;
    wire user_lnk_up;

    // Interrupt Signals
    wire usr_irq_req;
    wire usr_irq_ack;

    // -------------------------------------------------------------------------
    // 2. AXI Bus Signals
    // -------------------------------------------------------------------------
    // XDMA AXI-Lite Control Bus (BAR0 Mailbox 0x3F00)
    wire [31:0] xdma_axil_awaddr;
    wire        xdma_axil_awvalid;
    wire        xdma_axil_awready;
    wire [31:0] xdma_axil_wdata;
    wire [3:0]  xdma_axil_wstrb;
    wire        xdma_axil_wvalid;
    wire        xdma_axil_wready;
    wire [1:0]  xdma_axil_bresp;
    wire        xdma_axil_bvalid;
    wire        xdma_axil_bready;
    wire [31:0] xdma_axil_araddr;
    wire        xdma_axil_arvalid;
    wire        xdma_axil_arready;
    wire [31:0] xdma_axil_rdata;
    wire [1:0]  xdma_axil_rresp;
    wire        xdma_axil_rvalid;
    wire        xdma_axil_rready;

    // XDMA 64-bit AXI4-Full Master Signals
    wire [64:0] xdma_m_axi_awaddr;
    wire [7:0]  xdma_m_axi_awlen;
    wire        xdma_m_axi_awvalid;
    wire        xdma_m_axi_awready;
    wire [63:0] xdma_m_axi_wdata;
    wire [7:0]  xdma_m_axi_wstrb;
    wire        xdma_m_axi_wvalid;
    wire        xdma_m_axi_wready;
    wire        xdma_m_axi_bvalid;
    wire        xdma_m_axi_bready;
    wire [64:0] xdma_m_axi_araddr;
    wire [7:0]  xdma_m_axi_arlen;
    wire        xdma_m_axi_arvalid;
    wire        xdma_m_axi_arready;
    wire [63:0] xdma_m_axi_rdata;
    wire        xdma_m_axi_rvalid;
    wire        xdma_m_axi_rready;

    // Converted 256-bit XDMA AXI4 Master Signals
    wire [31:0] conv_m_axi_awaddr;
    wire [7:0]  conv_m_axi_awlen;
    wire        conv_m_axi_awvalid;
    wire        conv_m_axi_awready;
    wire [255:0] conv_m_axi_wdata;
    wire [31:0] conv_m_axi_wstrb;
    wire        conv_m_axi_wvalid;
    wire        conv_m_axi_wready;
    wire        conv_m_axi_bvalid;
    wire        conv_m_axi_bready;
    wire [31:0] conv_m_axi_araddr;
    wire [7:0]  conv_m_axi_arlen;
    wire        conv_m_axi_arvalid;
    wire        conv_m_axi_arready;
    wire [255:0] conv_m_axi_rdata;
    wire        conv_m_axi_rvalid;
    wire        conv_m_axi_rready;

    // GPGPU Compute Core 256-bit AXI4 Master Signals
    wire [63:0] core_m_axi_araddr;
    wire [7:0]  core_m_axi_arlen;
    wire        core_m_axi_arvalid;
    wire        core_m_axi_arready;
    wire [63:0] core_m_axi_rdata;
    wire        core_m_axi_rvalid;
    wire        core_m_axi_rready;
    wire [63:0] core_m_axi_awaddr;
    wire [7:0]  core_m_axi_awlen;
    wire        core_m_axi_awvalid;
    wire        core_m_axi_awready;
    wire [63:0] core_m_axi_wdata;
    wire        core_m_axi_wvalid;
    wire        core_m_axi_wready;

    // Crossbar 256-bit Master Signals to MIG DDR3
    wire [31:0] xbar_m_axi_awaddr;
    wire [7:0]  xbar_m_axi_awlen;
    wire        xbar_m_axi_awvalid;
    wire        xbar_m_axi_awready;
    wire [255:0] xbar_m_axi_wdata;
    wire [31:0] xbar_m_axi_wstrb;
    wire        xbar_m_axi_wvalid;
    wire        xbar_m_axi_wready;
    wire        xbar_m_axi_bvalid;
    wire        xbar_m_axi_bready;
    wire [31:0] xbar_m_axi_araddr;
    wire [7:0]  xbar_m_axi_arlen;
    wire        xbar_m_axi_arvalid;
    wire        xbar_m_axi_arready;
    wire [255:0] xbar_m_axi_rdata;
    wire        xbar_m_axi_rvalid;
    wire        xbar_m_axi_rready;

    // -------------------------------------------------------------------------
    // 3. PCIe XDMA Subsystem IP Instance (xdma_0)
    // -------------------------------------------------------------------------
    xdma_0 u_xdma (
        .sys_clk         (pcie_ref_clk),
        .sys_rst_n       (sys_rst_n),
        .user_lnk_up     (user_lnk_up),
        .axi_aclk        (axi_aclk),
        .axi_aresetn     (axi_aresetn),

        // PCIe PHY Transceiver Ports
        .pci_exp_rxp     (pci_exp_rxp),
        .pci_exp_rxn     (pci_exp_rxn),
        .pci_exp_txp     (pci_exp_txp),
        .pci_exp_txn     (pci_exp_txn),

        // Interrupt Ports
        .usr_irq_req     (usr_irq_req),
        .usr_irq_ack     (usr_irq_ack),
        .msi_enable      (),
        .msi_vector_width(),

        // BAR0 AXI4-Lite Control Bus (Mailbox 0x3F00)
        .m_axil_awaddr   (xdma_axil_awaddr),
        .m_axil_awvalid  (xdma_axil_awvalid),
        .m_axil_awready  (xdma_axil_awready),
        .m_axil_wdata    (xdma_axil_wdata),
        .m_axil_wstrb    (xdma_axil_wstrb),
        .m_axil_wvalid   (xdma_axil_wvalid),
        .m_axil_wready   (xdma_axil_wready),
        .m_axil_bresp    (xdma_axil_bresp),
        .m_axil_bvalid   (xdma_axil_bvalid),
        .m_axil_bready   (xdma_axil_bready),
        .m_axil_araddr   (xdma_axil_araddr),
        .m_axil_arvalid  (xdma_axil_arvalid),
        .m_axil_arready  (xdma_axil_arready),
        .m_axil_rdata    (xdma_axil_rdata),
        .m_axil_rresp    (xdma_axil_rresp),
        .m_axil_rvalid   (xdma_axil_rvalid),
        .m_axil_rready   (xdma_axil_rready),

        // 64-bit AXI4-Full Master DMA Bus
        .m_axi_awaddr    (xdma_m_axi_awaddr),
        .m_axi_awlen     (xdma_m_axi_awlen),
        .m_axi_awvalid   (xdma_m_axi_awvalid),
        .m_axi_awready   (xdma_m_axi_awready),
        .m_axi_wdata     (xdma_m_axi_wdata),
        .m_axi_wstrb     (xdma_m_axi_wstrb),
        .m_axi_wvalid    (xdma_m_axi_wvalid),
        .m_axi_wready    (xdma_m_axi_wready),
        .m_axi_bvalid    (xdma_m_axi_bvalid),
        .m_axi_bready    (xdma_m_axi_bready),
        .m_axi_araddr    (xdma_m_axi_araddr),
        .m_axi_arlen     (xdma_m_axi_arlen),
        .m_axi_arvalid   (xdma_m_axi_arvalid),
        .m_axi_arready   (xdma_m_axi_arready),
        .m_axi_rdata     (xdma_m_axi_rdata),
        .m_axi_rvalid    (xdma_m_axi_rvalid),
        .m_axi_rready    (xdma_m_axi_rready)
    );

    // -------------------------------------------------------------------------
    // 4. 64-bit to 256-bit AXI Data Width Converter Instance (axi_dwidth_converter_0)
    // -------------------------------------------------------------------------
    axi_dwidth_converter_0 u_dwidth_conv (
        .s_axi_aclk     (axi_aclk),
        .s_axi_aresetn  (axi_aresetn),

        // 64-bit Slave Interface from XDMA
        .s_axi_awaddr   (xdma_m_axi_awaddr[31:0]),
        .s_axi_awlen    (xdma_m_axi_awlen),
        .s_axi_awvalid  (xdma_m_axi_awvalid),
        .s_axi_awready  (xdma_m_axi_awready),
        .s_axi_wdata    (xdma_m_axi_wdata),
        .s_axi_wstrb    (xdma_m_axi_wstrb),
        .s_axi_wvalid   (xdma_m_axi_wvalid),
        .s_axi_wready   (xdma_m_axi_wready),
        .s_axi_bvalid   (xdma_m_axi_bvalid),
        .s_axi_bready   (xdma_m_axi_bready),
        .s_axi_araddr   (xdma_m_axi_araddr[31:0]),
        .s_axi_arlen    (xdma_m_axi_arlen),
        .s_axi_arvalid  (xdma_m_axi_arvalid),
        .s_axi_arready  (xdma_m_axi_arready),
        .s_axi_rdata    (xdma_m_axi_rdata),
        .s_axi_rvalid   (xdma_m_axi_rvalid),
        .s_axi_rready   (xdma_m_axi_rready),

        // 256-bit Master Interface to Crossbar S00
        .m_axi_awaddr   (conv_m_axi_awaddr),
        .m_axi_awlen    (conv_m_axi_awlen),
        .m_axi_awvalid  (conv_m_axi_awvalid),
        .m_axi_awready  (conv_m_axi_awready),
        .m_axi_wdata    (conv_m_axi_wdata),
        .m_axi_wstrb    (conv_m_axi_wstrb),
        .m_axi_wvalid   (conv_m_axi_wvalid),
        .m_axi_wready   (conv_m_axi_wready),
        .m_axi_bvalid   (conv_m_axi_bvalid),
        .m_axi_bready   (conv_m_axi_bready),
        .m_axi_araddr   (conv_m_axi_araddr),
        .m_axi_arlen    (conv_m_axi_arlen),
        .m_axi_arvalid  (conv_m_axi_arvalid),
        .m_axi_arready  (conv_m_axi_arready),
        .m_axi_rdata    (conv_m_axi_rdata),
        .m_axi_rvalid   (conv_m_axi_rvalid),
        .m_axi_rready   (conv_m_axi_rready)
    );

    // -------------------------------------------------------------------------
    // 5. 256-bit 2-in 1-out AXI Crossbar Interconnect Instance (axi_crossbar_0)
    // -------------------------------------------------------------------------
    axi_crossbar_0 u_crossbar (
        .aclk           (axi_aclk),
        .aresetn        (axi_aresetn),

        // Slave Port 0 (S00: Converted 256-bit Host PCIe DMA)
        .s_axi_awaddr   ({32'd0, conv_m_axi_awaddr}),
        .s_axi_awlen    ({8'd0, conv_m_axi_awlen}),
        .s_axi_awvalid  ({1'b0, conv_m_axi_awvalid}),
        .s_axi_awready  (conv_m_axi_awready),
        .s_axi_wdata    ({256'd0, conv_m_axi_wdata}),
        .s_axi_wstrb    ({32'd0, conv_m_axi_wstrb}),
        .s_axi_wvalid   ({1'b0, conv_m_axi_wvalid}),
        .s_axi_wready   (conv_m_axi_wready),
        .s_axi_bvalid   (conv_m_axi_bvalid),
        .s_axi_bready   ({1'b0, conv_m_axi_bready}),
        .s_axi_araddr   ({32'd0, conv_m_axi_araddr}),
        .s_axi_arlen    ({8'd0, conv_m_axi_arlen}),
        .s_axi_arvalid  ({1'b0, conv_m_axi_arvalid}),
        .s_axi_arready  (conv_m_axi_arready),
        .s_axi_rdata    (conv_m_axi_rdata),
        .s_axi_rvalid   (conv_m_axi_rvalid),
        .s_axi_rready   ({1'b0, conv_m_axi_rready}),

        // Master Port 0 (M00: 256-bit to MIG DDR3 S_AXI)
        .m_axi_awaddr   (xbar_m_axi_awaddr),
        .m_axi_awlen    (xbar_m_axi_awlen),
        .m_axi_awvalid  (xbar_m_axi_awvalid),
        .m_axi_awready  (xbar_m_axi_awready),
        .m_axi_wdata    (xbar_m_axi_wdata),
        .m_axi_wstrb    (xbar_m_axi_wstrb),
        .m_axi_wvalid   (xbar_m_axi_wvalid),
        .m_axi_wready   (xbar_m_axi_wready),
        .m_axi_bvalid   (xbar_m_axi_bvalid),
        .m_axi_bready   (xbar_m_axi_bready),
        .m_axi_araddr   (xbar_m_axi_araddr),
        .m_axi_arlen    (xbar_m_axi_arlen),
        .m_axi_arvalid  (xbar_m_axi_arvalid),
        .m_axi_arready  (xbar_m_axi_arready),
        .m_axi_rdata    (xbar_m_axi_rdata),
        .m_axi_rvalid   (xbar_m_axi_rvalid),
        .m_axi_rready   (xbar_m_axi_rready)
    );

    // -------------------------------------------------------------------------
    // 6. 1GB DDR3 VRAM Memory Interface Generator Instance (mig_7series_0)
    // -------------------------------------------------------------------------
    mig_7series_0 u_mig_ddr3 (
        // Memory physical pins
        .ddr3_dq        (ddr3_dq),
        .ddr3_dqs_n     (ddr3_dqs_n),
        .ddr3_dqs_p     (ddr3_dqs_p),
        .ddr3_addr      (ddr3_addr),
        .ddr3_ba        (ddr3_ba),
        .ddr3_ras_n     (ddr3_ras_n),
        .ddr3_cas_n     (ddr3_cas_n),
        .ddr3_we_n      (ddr3_we_n),
        .ddr3_reset_n   (ddr3_reset_n),
        .ddr3_ck_p      (ddr3_ck_p),
        .ddr3_ck_n      (ddr3_ck_n),
        .ddr3_cke       (ddr3_cke),
        .ddr3_dm        (ddr3_dm),
        .ddr3_odt       (ddr3_odt),

        // System clocks & calibration
        .sys_clk_p      (sys_clk_clk_p),
        .sys_clk_n      (sys_clk_clk_n),
        .sys_rst        (sys_rst_n),
        .ui_clk         (),
        .ui_clk_sync_rst(),
        .init_calib_complete(),

        // 256-bit AXI4 Slave Interface from Crossbar M00
        .s_axi_awid     (4'd0),
        .s_axi_awaddr   (xbar_m_axi_awaddr),
        .s_axi_awlen    (xbar_m_axi_awlen),
        .s_axi_awsize   (3'd5), // 256-bit burst = 32 bytes (2^5)
        .s_axi_awburst  (2'b01),
        .s_axi_awlock   (1'b0),
        .s_axi_awcache  (4'b0011),
        .s_axi_awprot   (3'b000),
        .s_axi_awqos    (4'b0000),
        .s_axi_awvalid  (xbar_m_axi_awvalid),
        .s_axi_awready  (xbar_m_axi_awready),
        .s_axi_wdata    (xbar_m_axi_wdata),
        .s_axi_wstrb    (xbar_m_axi_wstrb),
        .s_axi_wlast    (1'b1),
        .s_axi_wvalid   (xbar_m_axi_wvalid),
        .s_axi_wready   (xbar_m_axi_wready),
        .s_axi_bready   (xbar_m_axi_bready),
        .s_axi_bvalid   (xbar_m_axi_bvalid),
        .s_axi_bid      (),
        .s_axi_bresp    (),

        .s_axi_arid     (4'd0),
        .s_axi_araddr   (xbar_m_axi_araddr),
        .s_axi_arlen    (xbar_m_axi_arlen),
        .s_axi_arsize   (3'd5),
        .s_axi_arburst  (2'b01),
        .s_axi_arlock   (1'b0),
        .s_axi_arcache  (4'b0011),
        .s_axi_arprot   (3'b000),
        .s_axi_arqos    (4'b0000),
        .s_axi_arvalid  (xbar_m_axi_arvalid),
        .s_axi_arready  (xbar_m_axi_arready),
        .s_axi_rready   (xbar_m_axi_rready),
        .s_axi_rdata    (xbar_m_axi_rdata),
        .s_axi_rvalid   (xbar_m_axi_rvalid),
        .s_axi_rid      (),
        .s_axi_rresp    (),
        .s_axi_rlast    ()
    );

    // -------------------------------------------------------------------------
    // 7. RISC-V Command Processor (CP) SoC Instance (PicoRV32 + 16KB Mailbox 0x3F00)
    // -------------------------------------------------------------------------
    wire [31:0] compute_opcode;
    wire        cp_trap;

    riscv_cp_system u_riscv_cp (
        .clk                    (axi_aclk),
        .rst_n                  (axi_aresetn),

        // PCIe XDMA BAR0 AXI-Lite Slave Interface
        .s_axi_awvalid          (xdma_axil_awvalid),
        .s_axi_awready          (xdma_axil_awready),
        .s_axi_awaddr           (xdma_axil_awaddr),
        .s_axi_wvalid           (xdma_axil_wvalid),
        .s_axi_wready           (xdma_axil_wready),
        .s_axi_wdata            (xdma_axil_wdata),
        .s_axi_wstrb            (xdma_axil_wstrb),
        .s_axi_bvalid           (xdma_axil_bvalid),
        .s_axi_bready           (xdma_axil_bready),

        .s_axi_arvalid          (xdma_axil_arvalid),
        .s_axi_arready          (xdma_axil_arready),
        .s_axi_araddr           (xdma_axil_araddr),
        .s_axi_rvalid           (xdma_axil_rvalid),
        .s_axi_rready           (xdma_axil_rready),
        .s_axi_rdata            (xdma_axil_rdata),

        // GPU Compute Core Register Interface (0x4000_0000)
        .gpu_axi_awvalid        (),
        .gpu_axi_awready        (1'b1),
        .gpu_axi_awaddr         (),
        .gpu_axi_wvalid         (),
        .gpu_axi_wready         (1'b1),
        .gpu_axi_wdata          (compute_opcode),
        .gpu_axi_wstrb          (),
        .gpu_axi_bvalid         (1'b1),
        .gpu_axi_bready         (),

        .gpu_axi_arvalid        (),
        .gpu_axi_arready        (1'b1),
        .gpu_axi_araddr         (),
        .gpu_axi_rvalid         (1'b1),
        .gpu_axi_rready         (),
        .gpu_axi_rdata          (32'd0),

        .trap_out               (cp_trap)
    );

    // -------------------------------------------------------------------------
    // 8. Framebuffer & HDMI Display Pipeline Instances
    // -------------------------------------------------------------------------
    wire        fb_we;
    wire [18:0] fb_addr;
    wire [23:0] fb_rgb;

    framebuffer_ram #(
        .H_RES(640),
        .V_RES(480),
        .DATA_WIDTH(24)
    ) u_framebuffer (
        .clk_gpu                (axi_aclk),
        .we_gpu                 (fb_we),
        .addr_gpu               (fb_addr),
        .din_gpu                (fb_rgb),
        .clk_pix                (hdmi_clk),
        .addr_pix               (fb_addr),
        .dout_pix               ()
    );

    hdmi_top u_hdmi (
        .sys_clk_125m          (axi_aclk),
        .rst_n                 (axi_aresetn),
        .hdmi_nreset           (hdmi_nreset),
        .hdmi_clk              (hdmi_clk),
        .hdmi_hs               (hdmi_hs),
        .hdmi_vs               (hdmi_vs),
        .hdmi_de               (hdmi_de),
        .hdmi_d                (hdmi_d),
        .hdmi_scl              (hdmi_scl),
        .hdmi_sda              (hdmi_sda),
        .hdmi_init_done        (hdmi_init_done)
    );

    // -------------------------------------------------------------------------
    // 9. GPGPU Streaming Multiprocessor (SM) Compute Core Instance
    // -------------------------------------------------------------------------
    gpu_compute_core #(
        .C_AXIS_DATA_WIDTH(64)
    ) u_compute_core (
        .clk                    (axi_aclk),
        .rst_n                  (axi_aresetn),
        .opcode                 (compute_opcode),
        .launch_en              (1'b1),
        .grid_dim_x             (16'd16),
        .grid_dim_y             (16'd1),
        .block_dim_x            (16'd64),
        .block_dim_y            (16'd1),
        .src_vram_addr          (64'h0000_0000_8000_0000),
        .dst_vram_addr          (64'h0000_0000_8000_1000),
        .grid_done              (),

        // AXI4-Full Master Interface (256-bit to Crossbar S01)
        .m_axi_gmem_araddr      (core_m_axi_araddr),
        .m_axi_gmem_arlen       (core_m_axi_arlen),
        .m_axi_gmem_arvalid     (core_m_axi_arvalid),
        .m_axi_gmem_arready     (core_m_axi_arready),
        .m_axi_gmem_rdata       (core_m_axi_rdata),
        .m_axi_gmem_rvalid      (core_m_axi_rvalid),
        .m_axi_gmem_rready      (core_m_axi_rready),
        .m_axi_gmem_awaddr      (core_m_axi_awaddr),
        .m_axi_gmem_awlen       (core_m_axi_awlen),
        .m_axi_gmem_awvalid     (core_m_axi_awvalid),
        .m_axi_gmem_awready     (core_m_axi_awready),
        .m_axi_gmem_wdata       (core_m_axi_wdata),
        .m_axi_gmem_wvalid      (core_m_axi_wvalid),
        .m_axi_gmem_wready      (core_m_axi_wready),

        .s_axis_tdata           (64'd0),
        .s_axis_tkeep           (8'd0),
        .s_axis_tvalid          (1'b0),
        .s_axis_tready          (),
        .s_axis_tlast           (1'b0),
        .m_axis_tdata           (),
        .m_axis_tkeep           (),
        .m_axis_tvalid          (),
        .m_axis_tready          (1'b1),
        .m_axis_tlast           (),
        .fb_we                  (fb_we),
        .fb_addr                (fb_addr),
        .fb_rgb                 (fb_rgb)
    );

endmodule
